"""Init schema for rowing club data

Revision ID: 6af38957fbda
Revises: 3b2ee63c51f1
Create Date: 2026-02-09 22:25:40.909141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6af38957fbda'
down_revision: Union[str, Sequence[str], None] = '3b2ee63c51f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MemberRole',
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('Product',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_description', sa.TEXT(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('date_introduced', sa.DATE(), nullable=True),
    sa.Column('time_modified', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('Semester',
    sa.Column('semester', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('semester')
    )
    op.create_table('RolePermissions',
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_site', sa.Boolean(), nullable=False),
    sa.Column('create_announcements', sa.Boolean(), nullable=False),
    sa.Column('manage_dates', sa.Boolean(), nullable=False),
    sa.Column('manage_members', sa.Boolean(), nullable=False),
    sa.Column('manage_roles', sa.Boolean(), nullable=False),
    sa.Column('view_funds', sa.Boolean(), nullable=False),
    sa.Column('view_roster', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['MemberRole.role'], ),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('User',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('passwd_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=True),
    sa.Column('time_modified', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['MemberRole.role'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Coxwain',
    sa.Column('cox_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cox_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('cox_id')
    )
    op.create_table('CoxwainEvaluation',
    sa.Column('cox_id', sa.Uuid(), nullable=False),
    sa.Column('semester', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['cox_id'], ['User.uid'], ),
    sa.ForeignKeyConstraint(['semester'], ['Semester.semester'], ),
    sa.PrimaryKeyConstraint('cox_id')
    )
    op.create_index(op.f('ix_CoxwainEvaluation_semester'), 'CoxwainEvaluation', ['semester'], unique=False)
    op.create_table('MemberEnrollmentHistory',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dues_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['MemberRole.role'], ),
    sa.ForeignKeyConstraint(['semester'], ['Semester.semester'], ),
    sa.ForeignKeyConstraint(['uid'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'year', 'semester')
    )
    op.create_table('Rower',
    sa.Column('rower_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rower_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('rower_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rower')
    op.drop_table('MemberEnrollmentHistory')
    op.drop_index(op.f('ix_CoxwainEvaluation_semester'), table_name='CoxwainEvaluation')
    op.drop_table('CoxwainEvaluation')
    op.drop_table('Coxwain')
    op.drop_table('User')
    op.drop_table('RolePermissions')
    op.drop_table('Semester')
    op.drop_table('Product')
    op.drop_table('MemberRole')
    # ### end Alembic commands ###