"""init db v2

Revision ID: a56fa64287e8
Revises: 2247205d2674
Create Date: 2026-02-08 12:23:07.600489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a56fa64287e8'
down_revision: Union[str, Sequence[str], None] = '2247205d2674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_description', sa.TEXT(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('date_introduced', sa.DATE(), nullable=True),
    sa.Column('time_modified', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('Users',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('passwd_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=True),
    sa.Column('time_modified', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_Users_role'), 'Users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_role'), table_name='Users')
    op.drop_table('Users')
    op.drop_table('Products')
    # ### end Alembic commands ###